### PR TITLE
Jason's ver of add-login-form

### PR DESCRIPTION
**Pull request by jasondcater**
@graft I took all of your changes from `graft-add-login-form` and did a bit more work on it.

On the UI side of things I've made minor graphical changes to the login form and removed a bunch of pages that are not needed.

On the Server side of things. I've made sure that the Shibboleth endpoint behaves as expected (tested on stage). I've also did a bit more work on the login end point. The root `/` of janus will now either deliver the web form OR it will bounce you to the shibboleth end point. 

If we use the web form there is a bit more logic there that checks for a valid token/cookie. If there is one it then sends you to the refer. No need to see/use the web form and login again.

You can either merge my changes into your branch and then master OR just merge this branch into master. Either way will end up containing your work and mine.

### CODE REVIEW

**Comment by graft** [comment]
Looks good generally - a few nitpicks:

1) In #login_shib I believe with the new Etna::ParseBody the QUERY_STRING should get parsed into @params - might want to check this. If not, we should alter ParseBody so it DOES have this behavior, I think it is much cleaner than having to hunt through the various places in the @request.env object, and you won't need an 'extract_refer' method.

2) also in #pull_token_from_cookie, @request.cookies exists and should obviate this entire method - also just a note, in some places you have a tendency to bowdlerize vowels (i.e. 'tkn' instead of 'token') - I think full words are always better.

3) Regarding the endpoints, I don't see a need to have /validate-login instead of /login, since the POST verb should distinguish the routing just fine, but that's not a big deal. Regarding the shib endpoint, if shibboleth is protecting /login (which happens at the Apache level), the router will never respond to the /login endpoint, so there is no need for a separate /login_shib endpoint.

To merge this I should first merge the mountetna/etna PR?

**Comment by jasondcater** [comment]
All points taken. Didn't know about points 1 & 2 so thanks for the heads up
:-)

'jc-add-login-form' has everything. You can just merge that for simplicity.

I'll fix the three items on Tues unless you get to them first.

**Comment by graft** [comment]
I mean that this https://github.com/mountetna/etna/pull/1 must close first.

**Comment by jasondcater** [comment]
Just a reply to comment made by @graft who said: <u>"Regarding the shib endpoint, if shibboleth is protecting /login (which happens at the Apache level), the router will never respond to the /login endpoint, so there is no need for a separate /login_shib endpoint."</u>

Two separate end-points are still needed. One for the regular login and one for the shibboleth login. The way they janus checks authorization and sets the auth tokens is different for each method.

**Pull request merged**
